#!/usr/bin/env python3
"""NSFW mode is a full sprite swap — not an overlay on the clothed pet.

Uses the user-provided side-lying reference. Original clothed PNGs are never
overwritten. Idle / squint / sleep share the same still (no extra motion).
"""
from __future__ import annotations

import base64
from io import BytesIO
from pathlib import Path

from PIL import Image
from rembg import new_session, remove

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "assets"
OUT = SRC / "nsfw"
REF = SRC / "ref" / "pet_nsfw_comfy.png"
CANVAS_W, CANVAS_H = 1376, 768
PAD = 20


def cutout(path: Path) -> Image.Image:
    session = new_session("u2net")
    out = remove(path.read_bytes(), session=session)
    return Image.open(BytesIO(out)).convert("RGBA")


def fit_canvas(im: Image.Image) -> Image.Image:
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)

    max_w, max_h = CANVAS_W - PAD * 2, CANVAS_H - PAD * 2
    scale = min(max_w / im.width, max_h / im.height)
    nw, nh = max(1, int(im.width * scale)), max(1, int(im.height * scale))
    im = im.resize((nw, nh), Image.Resampling.LANCZOS)

    canvas = Image.new("RGBA", (CANVAS_W, CANVAS_H), (0, 0, 0, 0))
    x = (CANVAS_W - nw) // 2
    y = CANVAS_H - PAD - nh
    canvas.paste(im, (x, y), im)
    return canvas


def main() -> None:
    if not REF.exists():
        raise SystemExit(f"missing pose reference: {REF}")

    OUT.mkdir(parents=True, exist_ok=True)
    sprite = fit_canvas(cutout(REF))
    for name in ("pet_idle.png", "pet_squint.png", "pet_sleep.png"):
        sprite.save(OUT / name, optimize=True)
        print(f"[nsfw] wrote {name} {sprite.size}")

    preview = sprite.resize((688, 384), Image.Resampling.LANCZOS)
    preview.save(ROOT / "scratch_nsfw_preview.png")

    raw = (OUT / "pet_idle.png").read_bytes()
    uri = "data:image/png;base64," + base64.b64encode(raw).decode("ascii")
    ts_path = SRC / "nsfwSprites.ts"
    ts_path.write_text(
        "// Auto-generated by scripts/make_nsfw_sprites.py — do not edit by hand.\n"
        f'export const petIdleNsfw = "{uri}"\n'
        "export const petSquintNsfw = petIdleNsfw\n"
        "export const petSleepNsfw = petIdleNsfw\n",
        encoding="utf-8",
    )
    print(f"[nsfw] wrote {ts_path} ({ts_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
